"""add Department

Revision ID: 951bcc938817
Revises: da9687973e9e
Create Date: 2024-07-01 20:58:33.098107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951bcc938817'
down_revision = 'da9687973e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
